apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_USERNAME: {{ .Values.config.dbUser | quote }}
  DB_PASSWORD: "dev_pass123"
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
